version: '3.7'

services:
  web:
    build: ./pacnc
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pacnc/:/usr/src/pacnc/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

#   db:
#     image: postgres:12.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=nirav
#       - POSTGRES_PASSWORD=hello_django
#       - POSTGRES_DB=hello_django_dev

# volumes:
#   postgres_data:
